# Describes the format for Habitica service
api_call:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: habitica
    path:
      required: true
      example: '["tasks", "user", "post"]'
      selector:
        object:
    args:
      example: '{"text": "Use API from Home Assistant", "type": "todo"}'
      selector:
        object:
