set_profile_fan_speed_home:
  fields:
    fan_speed:
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

set_profile_fan_speed_away:
  fields:
    fan_speed:
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

set_profile_fan_speed_boost:
  fields:
    fan_speed:
      required: true
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

set_profile:
  fields:
    profile:
      required: true
      selector:
        select:
          options:
            - "Home"
            - "Away"
            - "Boost"
            - "Fireplace"
            - "Extra"
    duration:
      required: false
      selector:
        number:
          min: 1
          max: 65535
          unit_of_measurement: "min"
