# Describes the format for available opentherm_gw services

reboot_gateway:
  target:
    entity:
      integration: opentherm_gw

reset_gateway:
  target:
    entity:
      integration: opentherm_gw

set_central_heating_ovrd:
  target:
    entity:
      integration: opentherm_gw
  fields:
    ch_override:
      required: true
      selector:
        boolean:

set_clock:
  target:
    entity:
      integration: opentherm_gw
  fields:
    datetime:
      selector:
        datetime:

set_control_setpoint:
  target:
    entity:
      integration: opentherm_gw
  fields:
    temperature:
      required: true
      selector:
        number:
          min: 0
          max: 90
          step: 0.1
          unit_of_measurement: "째"

set_hot_water_ovrd:
  target:
    entity:
      integration: opentherm_gw
  fields:
    dhw_override:
      required: true
      example: "1"
      selector:
        text:

set_hot_water_setpoint:
  target:
    entity:
      integration: opentherm_gw
  fields:
    temperature:
      required: true
      selector:
        number:
          min: 0
          max: 90
          step: 0.1
          unit_of_measurement: "째"

set_gpio_mode:
  target:
    entity:
      integration: opentherm_gw
  fields:
    id:
      required: true
      selector:
        select:
          options:
            - "A"
            - "B"
    mode:
      required: true
      selector:
        number:
          min: 0
          max: 7

set_led_mode:
  target:
    entity:
      integration: opentherm_gw
  fields:
    id:
      required: true
      selector:
        select:
          options:
            - "A"
            - "B"
            - "C"
            - "D"
            - "E"
            - "F"
    mode:
      required: true
      selector:
        select:
          options:
            - "B"
            - "C"
            - "E"
            - "F"
            - "H"
            - "M"
            - "O"
            - "P"
            - "R"
            - "T"
            - "W"
            - "X"

set_max_modulation:
  target:
    entity:
      integration: opentherm_gw
  fields:
    level:
      required: true
      selector:
        number:
          min: -1
          max: 100

set_outside_temperature:
  target:
    entity:
      integration: opentherm_gw
  fields:
    temperature:
      required: true
      selector:
        number:
          min: -40
          max: 99
          unit_of_measurement: "째"

set_setback_temperature:
  target:
    entity:
      integration: opentherm_gw
  fields:
    temperature:
      required: true
      selector:
        number:
          min: 0
          max: 30
          step: 0.1
          unit_of_measurement: "째"

send_transparent_command:
  target:
    entity:
      integration: opentherm_gw
  fields:
    transp_cmd:
      required: true
      selector:
        text:
    transp_arg:
      required: true
      selector:
        text:
