get_mealplan:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: mealie
    start_date:
      selector:
        date:
    end_date:
      selector:
        date:
